### ISSUE TITLE
Sugestao pro landing page

### ISSUE THREAD

**Issue by carlisia** [gopherconbr/gopherconbr.org#10]
O gophie no qiadrado eu colocaria a direira do botao, e os outros ou nao colocaria ou colocaria a esquerda (mas lembrando que eu nao sou designer :smile:)

No minimo, eu alinharinha no centro, parece que eles tao mais pra esquerda

![image](https://cloud.githubusercontent.com/assets/16508/17078329/09786cca-50a5-11e6-9fe3-a1c492964660.png)

**Comment by rrmartins** [comment]
@carlisia acho que ficou legal assim...

**Comment by carlisia** [comment]
Eh talvez esteja bom. :)

**Comment by carlisia** [comment]
Vamos deixar assim por hora.
