### ISSUE TITLE
Traduzir o CoC pra portugues

### ISSUE THREAD

**Issue by carlisia** [gopherconbr/gopherconbr.org#12]
Quando resolver o #9, vai precisar traduzir o CoC pro portugues.

**Comment by rrmartins** [comment]
@carlisia confirma ai: 
https://gist.github.com/carlisia/3797e1d2f2dfb32ab00967d54ffe1caf#gistcomment-1832535

**Comment by vdemario** [comment]
Eu fiz um comentário no gist, mas acho que podia abrir o PR já pra fazer comentário inline que flui melhor.

**Comment by carlisia** [comment]
@rrmartins o comentario do @vdemario foi avaliado? Pode fechar?

**Comment by rrmartins** [comment]
@carlisia @vdemario atualizei no PR https://github.com/gopherconbr/gopherconbr.org/pull/22

@vdemario, comentei lá. temos um PR aberto .. :) a expressão _podem ser sancionado_  acho que tem o sentido de que a pessoa será observada com mais rigidez, e um paragrafo pra baixo, fala de que nós levaremos o caso as autoridades locais.
