### ISSUE TITLE
Traduzir o website para ingles

### ISSUE THREAD

**Issue by carlisia** [gopherconbr/gopherconbr.org#13]
Quando o #8 estiver pronto.

**Comment by carlisia** [comment]
@rrmartins https://2016.gopherconbr.org/en/ Nao tem nada??

**Comment by rrmartins** [comment]
@carlisia criei um PR https://github.com/gopherconbr/gopherconbr.org/pull/24 para podermos ver isso... estou invocando as forças do @guilhermebr para mexer no _Caddy_ kkkk o sono me atrapalhou aqui kkk

**Comment by carlisia** [comment]
Ok!
