### ISSUE TITLE
Reduzir as fotos do hotel 

### ISSUE THREAD

**Issue by carlisia** [gopherconbr/gopherconbr.org#15]
Eu removeria as fotos marcadas com X, e adicionaria 2 fotos do salao de conferencia. Assim ficariam a foto grande e linda do hotel na esquerda, e quatro menores a direita, e nao ficaria o espaco em branco a esquerda. Ainda assim ficaria um espaco pequeno em branco a esquerda, se tiver algum CSS ninja que pudesse alinhar seria muito bom.

![image](https://cloud.githubusercontent.com/assets/16508/17078357/f3cf90aa-50a5-11e6-90dd-eb458f6cc51d.png)

**Comment by rrmartins** [comment]
👍 show... o que acha em colocar mais umas fotos do salao?

**Comment by carlisia** [comment]
Si, eu adicionaria pelo menos 2.

**Comment by rrmartins** [comment]
sim, no lugar dos dois primeiros `x` colocamos duas do salao, ai ficaria 4 fotos (2 salao, 1 restaurante, 1 piscina). 

Ficaria assim:

![screen shot 2016-07-23 at 11 25 33](https://cloud.githubusercontent.com/assets/455676/17078376/36812d74-50c8-11e6-8aa0-4fa4e239d0d4.png)

o que acha?

**Comment by carlisia** [comment]
Isso estah perfeito!

**Comment by rrmartins** [comment]
PR https://github.com/gopherconbr/gopherconbr.org/pull/16 ta lá :)
