### ISSUE TITLE
Video de background mostrando legenda

### ISSUE THREAD

**Issue by guilhermebr** [gopherconbr/gopherconbr.org#17]
Possivel solução: mexer no css,  .video-header e aumentar o video...

No theme gophercon está ok, mas não consegui fazer o mesmo no gopherconbr

para ver a verão do gophercon: hugo server -v -w -t=gophercon

**Comment by rrmartins** [comment]
Acho que a @carlisia já mexeu nisso, confere ? :) 

no https://2016.gopherconbr.org/#top não vi a legenda aparecer..

**Comment by carlisia** [comment]
Alguem consertou!
