### ISSUE TITLE
Logo está serrilhado

### ISSUE THREAD

**Issue by vdemario** [gopherconbr/gopherconbr.org#20]
Aparece assim pra mais alguém também?

![logo_serrilhado](https://cloud.githubusercontent.com/assets/6087424/17080071/3962f622-50f9-11e6-9a4f-acdc6056b9d3.png)

Vi desse jeito no mac e no windows, ambos chrome.

Não sei como resolve, mas pra mim chama atenção contra o fundo.

**Comment by ebonet** [comment]
Ele tá em png ou svg? Daria pra vetorizar esse logo (Facilitaria até pra confecção de swag depois)

**Comment by carlisia** [comment]
Essa nao eh a versao final do logo! Vou fechar pq a versao final estah a caminho 👍
