### ISSUE TITLE
Incluir local do workshop

### ISSUE THREAD

**Issue by carlisia** [gopherconbr/gopherconbr.org#27]
Na sessao de Local, deveria incluir o local do workshop (Resultados Digitais) pra ficar claro que nao serah no mesmo lugar.

Portugues e ingles.

![image](https://cloud.githubusercontent.com/assets/16508/17084831/27f54690-517d-11e6-9a36-ae10b2277c0c.png)

**Comment by andrewsmedina** [comment]
acho melhor deixar o hotel como local e quando tivermos a grade colocar essa informação no dia 13.

Um exemplo: http://2016.pythonbrasil.org.br/#schedule

**Comment by rrmartins** [comment]
Tambem acho melhor centralizar tudo no hotel.

**Comment by carlisia** [comment]
`centralizar tudo no hotel.` nao eh opcao. Jah foi arranjado para o workshop ser em outro local.

**Comment by carlisia** [comment]
@andrewsmedina a racional para incluir na pagina principal (alem de incluir tambem em todo lugar onde local for referenciado) eh para reforcar o fato que existe o segundo local para o workshop. Qual seria a racional para nao incluir?

**Comment by andrewsmedina** [comment]
quase todos os eventos, tratam o dia do workshop como dia a parte, pelo fato do workshop alcançar uma quantidade de pessoas menor.

e dar mesmo destaque do lugar onde vai ser a conferencia para o lugar do workshop, implica em coisas como: "teremos fotos do lugar do workshop tambem?"

**Comment by carlisia** [comment]
Nao eh necessario ter foto do local do workshop.

Eu vi a mudanca que voce fez, voce achou que ficou legal?

**Comment by rrmartins** [comment]
@carlisia não sabia disso do local . 😊

Sent using CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=7.11.24&pv=9.3.1&source=email_footer_2]
On Sun, Jul 24, 2016 at 23:33, Andrews Medina <notifications@github.com> wrote:
quase todos os eventos, tratam o dia do workshop como dia a parte, pelo fato do workshop alcançar uma quantidade de pessoas menor.

e dar mesmo destaque do lugar onde vai ser a conferencia para o lugar do workshop, implica em coisas como: "teremos fotos do lugar do workshop tambem?"

**Comment by carlisia** [comment]
👍
