### ISSUE TITLE
Adicionar um CTA para potenciais patrocinadores

### ISSUE THREAD

**Issue by carlisia** [gopherconbr/gopherconbr.org#28]
Na pagina principal, abaixo dos logos, poderiamos ter um CTA como esse:

![image](https://cloud.githubusercontent.com/assets/16508/17084219/793b8e34-516d-11e6-850b-1ca0ab4f5af1.png)

Esse link aponta para o pdf do plano de patrocino.

pt e en

**Comment by rrmartins** [comment]
já temos um plano de patrocinio?

**Comment by carlisia** [comment]
@rrmartins sim, tah prontinho, soh nao foi colocado no website ainda. O URL estah aqui: https://github.com/gopherconbr/gopherconbr.org/issues/26
