### ISSUE TITLE
Incluir opcao de mudar de locale

### ISSUE THREAD

**Issue by carlisia** [gopherconbr/gopherconbr.org#29]
Na pagina principal em pt-br precisa incluir uma opcao em algum lugar pra mudar pra versao em ingles.

Nao acho que o vice-versa (ter opcao de ir pro pt-br na versao em ingles) seja tao necessario, mas talvez seja, ou talvez seja simplismente pra manter consistencia.

**Comment by rrmartins** [comment]
Criei o PR ai... o que acham?
https://github.com/gopherconbr/gopherconbr.org/pull/30

**Comment by carlisia** [comment]
👍
