### ISSUE TITLE
Incluir fotos do auditório da Resultados Digitais

### ISSUE THREAD

**Issue by ricardolonga** [gopherconbr/gopherconbr.org#50]
Fotos do local onde será ministrado o Workshop no dia 6 de novembro.

![3](https://cloud.githubusercontent.com/assets/1022655/17173593/12e4d4d0-53d2-11e6-8019-9df98cac7478.jpg)
![1](https://cloud.githubusercontent.com/assets/1022655/17173594/12f56390-53d2-11e6-9163-993a460798a9.jpg)

**Comment by carlisia** [comment]
Nao sei se gostei dessas fotos pro site. Nao eh a configuracao que seria no workshop do Bill, que vai precisar de mesas.

**Comment by ricardolonga** [comment]
Mesas? Para cada participante?

**Comment by carlisia** [comment]
? Eh um workshop, nao uma palestra. Eles nao tem desks?

Sent from my iphone




On Thu, Jul 28, 2016 at 9:30 AM -0700, "Ricardo Longa" <notifications@github.com> wrote:












Mesas? Para cada participante?

**Comment by ricardolonga** [comment]
Creio que não, vou questioná-los.

**Comment by vdemario** [comment]
Podemos fechar esse issue? Acho que não tem mais sentido.

**Comment by carlisia** [comment]
Sim

--------
Carlisia Campos
