### ISSUE TITLE
Data incorreta

### ISSUE THREAD

**Issue by carlisia** [gopherconbr/gopherconbr.org#60]
Acabei de postar em um grupo do Facebook e saiu com a data errada. Serah que isso anda eh cache? Nao achei no repo.

![image](https://cloud.githubusercontent.com/assets/16508/17272996/ef01374e-565a-11e6-9012-f2b007e44432.png)

**Comment by vdemario** [comment]
Qual foi a url q vc postou? Só a raiz do site?

**Comment by carlisia** [comment]
Exato.

Sent from my iphone




On Sun, Jul 31, 2016 at 12:48 PM -0700, "Vitor De Mario" <notifications@github.com> wrote:












Qual foi a url q vc postou? Só a raiz do site?

**Comment by vdemario** [comment]
Botei `gopherconbr.org` no https://developers.facebook.com/tools/debug/ (dica do @fsouza no Slack outro dia) e aparecem as datas certas.

Pode ser que apareçam resultados diferentes dependendo da localização.

**Comment by carlisia** [comment]
Vou fechar entao.
