### ISSUE TITLE
Add Johnny Boursiquot

### ISSUE THREAD

**Issue by carlisia** [gopherconbr/gopherconbr.org#68]
Twitter: @jboursiquot

Bio:

Johnny is a multi-disciplined Software Engineer with nearly two decades of industry experience spanning various server, client and mobile technologies. His past roles include developer, co-founder, teacher and CTO. He is currently the Principal Software Engineer at RBM Technologies in Boston.

His love for technology is matched only by his passion for community service. He is an organizer for the Boston Ruby Group and the Boston Golang Group, regularly serves as a teacher for various organizations that seek to diversify the tech industry and mentors a number of young technology professionals in the Boston area.

**Comment by jboursiquot** [comment]
Heads up @carlisia, some of that is out of date: 
`He is currently the Principal Software Engineer at RBM Technologies in Boston.` 
should be 
`He is currently the Principal Software Engineer at Achievement Network based in Boston.`

Aslo: 
`His love for technology is matched only by his passion for community service. He is an organizer for the Boston Ruby Group and the Boston Golang Group, regularly serves as a teacher for various organizations that seek to diversify the tech industry and mentors a number of young technology professionals in the Boston area.` 

should be 

`His love for technology is matched only by his passion for community service. He is a GoBridge Core Member, organizer of the Baltimore Golang user group and former organizer for Boston Ruby and Boston Golang. He regularly serves as a teacher for various organizations that seek to diversify the tech industry and mentors a number of young technology professionals in the Boston and Baltimore metro areas.`

**Comment by carlisia** [comment]
Ha, thanks a bunch @jboursiquot. I didn't even read it, just copied/pasted from the CFP. :)

**Comment by jboursiquot** [comment]
@carlisia No worries. I should probably update that info on PaperCall :)

**Comment by vdemario** [comment]
What about the picture? Can we use the one from your github profile, @jboursiquot ?

**Comment by jboursiquot** [comment]
@vdemario yep, that works.
