### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by carlisia** [gopherconbr/gopherconbr.org#9]
Eu tinha sugerido usar o CoC do GothamGo http://www.gothamgo.com/conduct, que eh bem mais apropriado pra um evento de conferencia do que o do Go https://golang.org/conduct:

Gostaria que fosse considerado. Votos?

**Comment by andrewsmedina** [comment]
+1 para usar odo gothamgo

**Comment by carlisia** [comment]
Acho que pode colocar no website entao, eh soh dar credito pra eles.

**Comment by rrmartins** [comment]
👍

**Comment by carlisia** [comment]
@rrmartins Jah ajustei o texto (ingles) pra colocar no CFP. Usa o mesmo por favor pra ficar igual:
